apiVersion: v1
kind: Namespace
metadata:
  name: food-info
  labels:
    name: food-info

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: food-info
  name: food-info-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: food-info
  labels:
    app: food-info-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-info-app
  template:
    metadata:
      labels:
        app: food-info-app
    spec:
      volumes:
      - name: deployment-volume
        persistentVolumeClaim:
          claimName: food-info-volume
      containers:
      - name: food-info-app
        image: food-info:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: "/food-info/db"
          name: deployment-volume

---

apiVersion: v1
kind: Service
metadata:
  namespace: food-info
  name: my-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: food-info-app
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 3000
      targetPort: 3000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30001
